### ISSUE TITLE
sidecar crashes when parsing malformed response

### ISSUE THREAD

**Issue by messersc** [Snakemake-Profiles/slurm#96]
Hi,

we have problems with the sidecar crashing. This happens when the response was empty as far as I can see from the logs. We are not sure why the response might be empty yet, but this case should be handled better. Log is below, I can post a PR if we decide on the best course of action.

Thanks,
Clemens

```
sbatch: routed your job to partition short
127.0.0.1 - - [23/May/2022 16:43:27] "POST /job/register/2042127 HTTP/1.1" 200 -
Submitted job 12 with external jobid '2042127'.
127.0.0.1 - - [23/May/2022 16:43:30] "GET /job/status/2042120 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:30] "GET /job/status/2042121 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:31] "GET /job/status/2042122 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:31] "GET /job/status/2042123 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:31] "GET /job/status/2042124 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:32] "GET /job/status/2042125 HTTP/1.1" 200 -
127.0.0.1 - - [23/May/2022 16:43:32] "GET /job/status/2042126 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 39810)
Traceback (most recent call last):
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/fast/users/USER_c/work/miniconda/envs/snakemake-slurm/lib/python3.10/http/server.py", line 413, in handle_one_request
    method()
  File "/etc/xdg/snakemake/cubi-v1/slurm-sidecar.py", line 211, in do_GET
    status = self.server.poll_thread.get_state(job_id)
  File "/etc/xdg/snakemake/cubi-v1/slurm-sidecar.py", line 104, in get_state
    self.states[jobid] = self._get_state_sacct(jobid)
  File "/etc/xdg/snakemake/cubi-v1/slurm-sidecar.py", line 131, in _get_state_sacct
    parsed = {x.split("|")[0]: x.split("|")[1] for x in output.strip().split("\n")}
  File "/etc/xdg/snakemake/cubi-v1/slurm-sidecar.py", line 131, in <dictcomp>
    parsed = {x.split("|")[0]: x.split("|")[1] for x in output.strip().split("\n")}
IndexError: list index out of range
----------------------------------------
slurm-status.py: could not query side car: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
list index out of range
Traceback (most recent call last):
  File "/etc/xdg/snakemake/cubi-v1/slurm-status.py", line 89, in <module>
    elif status.startswith("CANCELLED"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by mbhall88** [comment]
I'm actually still seeing similar behavious as this on HEAD... Is there a more robust way of dealing with this?

```
Submitted job 84 with external jobid '40190775'.
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 44616)
Traceback (most recent call last):
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/home/mihall/sw/miniconda3/envs/amplicon/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/mihall/.config/snakemake/slurm.punim1637/slurm-sidecar.py", line 213, in do_GET
    status = self.server.poll_thread.get_state(job_id)
  File "/home/mihall/.config/snakemake/slurm.punim1637/slurm-sidecar.py", line 106, in get_state
    self.states[jobid] = self._get_state_sacct(jobid)
  File "/home/mihall/.config/snakemake/slurm.punim1637/slurm-sidecar.py", line 133, in _get_state_sacct
    parsed = {x.split("|")[0]: x.split("|")[1] for x in output.strip().split("\n")}
  File "/home/mihall/.config/snakemake/slurm.punim1637/slurm-sidecar.py", line 133, in <dictcomp>
    parsed = {x.split("|")[0]: x.split("|")[1] for x in output.strip().split("\n")}
IndexError: list index out of range
----------------------------------------
slurm-status.py: could not query side car: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
list index out of range
```

**Comment by mbhall88** [comment]
Came across this again today. cc @holtgrewe

**Comment by mbhall88** [comment]
I'll give it a go, thanks

**Comment by ASLeonard** [comment]
I was getting this error a lot
```
    parsed = {x.split("|")[0]: x.split("|")[1] for x in output.strip().split("\n")}
IndexError: list index out of range
```

And that patch seems to have fixed it. I occasionally see warnings like `Could not parse '' (try 1 of 10)`, but the sidecar stays running and soon after the job is probably recorded.

**Comment by mbhall88** [comment]
This error is popping up on my slurm again all of a sudden. I tried applying that patch but 4/7 hunks failed. Is that patch with respect to the most recent `slurm-sidecar.py`?

**Comment by mbhall88** [comment]
The patch also worked for me too. I'll open a PR with that patch applied
